server:
  port: 8090

spring:
  application:
    name: config-server
#配置config-server 仓库地址
  cloud:
    config:
      server:
        git:
        #uri表示配置中心所在仓库的位置
          uri: https://gitee.com/ljxcoder/Config-repository
          #也可以使用通配符https://gitee.com/ljxcoder/｛application}-{profile}
          #实现一个远程持仓库对应一个微服务或环境
          username: ljxcoder
          password: ljx123
#配置安全认证          
  security:
    user:
      name: user
      password: pwd        
#向服务注册中心注册
eureka:
  client:
    service-url:
      defaultZone: http://user:pwd@peer1:8761/eureka/,http://user:pwd@peer2:8762/eureka/
               

 