#注册中心地址
eureka:
    client:
        service-url:
            defaultZone: http://user:pwd@peer1:8761/eureka,http://user:pwd@peer2:8762/eureka
#开启健康检查
        healthcheck:
          enabled: true
#端口号
server:
    port: 8765
#应用名称
spring:
    application:
        name: service-consumer
#忽略安全认证
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true


