eureka:
    client:
        service-url:
            defaultZone: http://user:pwd@peer1:8761/eureka,http://user:pwd@peer2:8762/eureka
server:
    port: 8765
spring:
    application:
        name: service-consumer
